version: '3.8'

services:
  mysql:
    build: ./mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Define a senha do root
      MYSQL_DATABASE: repo_arquivos      # Banco de dados a ser criado
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
   build:
     context: ./backend  # Caminho para a pasta do backend
     dockerfile: Dockerfile  # Nome do Dockerfile
   container_name: backend_container
   volumes:
     - ./.oci/config:/app/.oci/config
     - ./.oci/diegodalwitt@hotmail.com_2024-12-05T00_03_01.395Z.pem:/app/.oci/diegodalwitt@hotmail.com_2024-12-05T00_03_01.395Z.pem
     - ./backend:/app  # Garante o mapeamento correto da aplicação
   working_dir: /app
   command: ["python", "-m", "app.main"]  # Certifique-se de que é o comando correto
   ports:
     - "5000:5000"
   environment:
     PYTHONPATH: /app
     DB_HOST: mysql
     DB_NAME: repo_arquivos
     DB_USER: root
     DB_PASSWORD: rootpassword
     OCI_BUCKET_NAME: meu-bucket-seguro
     OCI_CONFIG_FILE: /app/.oci/config
     OCI_PROFILE: DEFAULT
     UPLOAD_DIR: /app/upload
   depends_on:
     - mysql
   restart: always

  frontend:
    image: nginx:latest
    container_name: frontend_container
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

